/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as AdminappRouteRouteImport } from './routes/admin/(app)/route'
import { Route as TinTucIndexRouteImport } from './routes/tin-tuc/index'
import { Route as TinTucSlugRouteImport } from './routes/tin-tuc/$slug'
import { Route as AdminappIndexRouteImport } from './routes/admin/(app)/index'
import { Route as AdminappSettingsRouteImport } from './routes/admin/(app)/settings'
import { Route as AdminauthSignInRouteImport } from './routes/admin/(auth)/sign-in'
import { Route as AdminauthSignUpRouteImport } from './routes/admin/(auth)/sign-up'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminappRouteRoute = AdminappRouteRouteImport.update({
  id: '/admin/(app)',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucIndexRoute = TinTucIndexRouteImport.update({
  id: '/tin-tuc/',
  path: '/tin-tuc/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucSlugRoute = TinTucSlugRouteImport.update({
  id: '/tin-tuc/$slug',
  path: '/tin-tuc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminappIndexRoute = AdminappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminappRouteRoute,
} as any)
const AdminappSettingsRoute = AdminappSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminappRouteRoute,
} as any)
const AdminauthSignInRoute = AdminauthSignInRouteImport.update({
  id: '/admin/(auth)/sign-in',
  path: '/admin/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminauthSignUpRoute = AdminauthSignUpRouteImport.update({
  id: '/admin/(auth)/sign-up',
  path: '/admin/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/admin': typeof AdminappRouteRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/tin-tuc/': typeof TinTucIndexRoute
  '/admin/settings': typeof AdminappSettingsRoute
  '/admin/sign-in': typeof AdminauthSignInRoute
  '/admin/sign-up': typeof AdminauthSignUpRoute
  '/admin/': typeof AdminappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/tin-tuc': typeof TinTucIndexRoute
  '/admin/settings': typeof AdminappSettingsRoute
  '/admin/sign-in': typeof AdminauthSignInRoute
  '/admin/sign-up': typeof AdminauthSignUpRoute
  '/admin': typeof AdminappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/admin/(app)': typeof AdminappRouteRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/tin-tuc/': typeof TinTucIndexRoute
  '/admin/(app)/settings': typeof AdminappSettingsRoute
  '/admin/(auth)/sign-in': typeof AdminauthSignInRoute
  '/admin/(auth)/sign-up': typeof AdminauthSignUpRoute
  '/admin/(app)/': typeof AdminappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dich-vu'
    | '/gioi-thieu'
    | '/lien-he'
    | '/admin'
    | '/tin-tuc/$slug'
    | '/tin-tuc/'
    | '/admin/settings'
    | '/admin/sign-in'
    | '/admin/sign-up'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dich-vu'
    | '/gioi-thieu'
    | '/lien-he'
    | '/tin-tuc/$slug'
    | '/tin-tuc'
    | '/admin/settings'
    | '/admin/sign-in'
    | '/admin/sign-up'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dich-vu'
    | '/gioi-thieu'
    | '/lien-he'
    | '/admin/(app)'
    | '/tin-tuc/$slug'
    | '/tin-tuc/'
    | '/admin/(app)/settings'
    | '/admin/(auth)/sign-in'
    | '/admin/(auth)/sign-up'
    | '/admin/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DichVuRoute: typeof DichVuRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  AdminappRouteRoute: typeof AdminappRouteRouteWithChildren
  TinTucSlugRoute: typeof TinTucSlugRoute
  TinTucIndexRoute: typeof TinTucIndexRoute
  AdminauthSignInRoute: typeof AdminauthSignInRoute
  AdminauthSignUpRoute: typeof AdminauthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/(app)': {
      id: '/admin/(app)'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminappRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc/': {
      id: '/tin-tuc/'
      path: '/tin-tuc'
      fullPath: '/tin-tuc/'
      preLoaderRoute: typeof TinTucIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc/$slug': {
      id: '/tin-tuc/$slug'
      path: '/tin-tuc/$slug'
      fullPath: '/tin-tuc/$slug'
      preLoaderRoute: typeof TinTucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/(app)/': {
      id: '/admin/(app)/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminappIndexRouteImport
      parentRoute: typeof AdminappRouteRoute
    }
    '/admin/(app)/settings': {
      id: '/admin/(app)/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminappSettingsRouteImport
      parentRoute: typeof AdminappRouteRoute
    }
    '/admin/(auth)/sign-in': {
      id: '/admin/(auth)/sign-in'
      path: '/admin/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminauthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/(auth)/sign-up': {
      id: '/admin/(auth)/sign-up'
      path: '/admin/sign-up'
      fullPath: '/admin/sign-up'
      preLoaderRoute: typeof AdminauthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminappRouteRouteChildren {
  AdminappSettingsRoute: typeof AdminappSettingsRoute
  AdminappIndexRoute: typeof AdminappIndexRoute
}

const AdminappRouteRouteChildren: AdminappRouteRouteChildren = {
  AdminappSettingsRoute: AdminappSettingsRoute,
  AdminappIndexRoute: AdminappIndexRoute,
}

const AdminappRouteRouteWithChildren = AdminappRouteRoute._addFileChildren(
  AdminappRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DichVuRoute: DichVuRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  AdminappRouteRoute: AdminappRouteRouteWithChildren,
  TinTucSlugRoute: TinTucSlugRoute,
  TinTucIndexRoute: TinTucIndexRoute,
  AdminauthSignInRoute: AdminauthSignInRoute,
  AdminauthSignUpRoute: AdminauthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
